# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "XUEQIANG LU"
# description              : "Research Assistant"
description              : "Postdoc <span><a href='https://drive.google.com/file/d/1ZmHxfHVHcqvccHRcslw-d5ZIsu7USN6h/view?usp=sharing'>[CV]</a><span>"
repository               : "luxueqiang/luxueqiang.github.io"
google_scholar_stats_use_cdn : true

# google analytics - get google_analytics_id from https://analytics.google.com/analytics/
google_analytics_id      : G-NXWEYZXBF3

# SEO Related
google_site_verification : 88a6EvCIxIKqnJSeIykz0kXh_JDYVJW34ZeH9R18sYU # get google_site_verification from https://search.google.com/search-console/about
bing_site_verification   : 94C10FA5467DD632CE13852838BDAAF8 # get bing_site_verification from https://www.bing.com/webmasters/about
baidu_site_verification  : codeva-Y3WfBJVakn # get baidu_site_verification from https://ziyuan.baidu.com/login/index?u=/site/index

# Site Author
author:
  name             : "XUEQIANG LU"
  avatar           : "images/XUEQIANG_LU.jpeg"
  bio              :
  location         : "Chengdu, China"
  employer         :
  pubmed           : 
  googlescholar    : "https://scholar.google.com/citations?user=YOUR_GOOGLE_SCHOLAR_ID&user=Bg80K9YAAAAJ"
  email            : "luxueqiang2018@gmail.com"
  researchgate     : "https://www.researchgate.net/profile/Xueqiang-Lu-2"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "luxueqiang"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      :
  lastfm           :
  linkedin         :
  dblp             :
  orcid            : "https://orcid.org/0000-0002-8457-1657"
  pinterest        :
  soundcloud       :
  stackoverflow    :
  steam            :
  tumblr           :
  twitter          : "LU_XUEQIANG"
  vine             :
  weibo            : "u/3722292894"
  xing             :
  youtube          :
  wikipedia        :


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: Asia/Shanghai # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development